# Project information
site_name: Monero Docs
site_description: 'Unofficial Monero Documentation'
site_author: "Piotr 'Qertoip' Włodarek"
site_url: 'https://monerodocs.org/'

pages:
- Home: 'index.md'
- Interacting: 'interacting/overview.md'
- Technical Specs: 'technical-specs.md'
- Primitives:
    - Base58: 'primitives/base58.md'
- Address:
    - Standard: 'public-address/standard-address.md'
    - Integrated: 'public-address/integrated-address.md'
    - Subaddress: 'public-address/subaddress.md'
- Multisignature: 'multisignature.md'

theme:
  name: 'material' # 'material'
  palette:
#    primary: 'Deep Orange'
    primary: 'Indigo'
    accent: 'Indigo'
#  logo: 'images/monero.svg'
  language: 'en'
#   feature:
#     tabs: true

extra_css: ['extra.css']

repo_name: 'monerodocs/md'
repo_url: 'https://github.com/monerodocs/md'
